name: tf18
channels:
  - defaults
dependencies:
  - absl-py=0.2.2=py36_0
  - asn1crypto=0.24.0=py36_0
  - astor=0.6.2=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=1.5.0=py36_0
  - boto=2.49.0=py36_0
  - boto3=1.8.2=py36_0
  - botocore=1.11.2=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py36_1
  - cffi=1.11.5=py36h74b6da3_1
  - chardet=3.0.4=py36_1
  - colorama=0.3.9=py36h029ae33_0
  - cryptography=2.3.1=py36h74b6da3_0
  - cudatoolkit=9.0=1
  - cudnn=7.1.4=cuda9.0_0
  - cycler=0.10.0=py36h009560c_0
  - cython=0.28.4=py36h6538335_0
  - decorator=4.3.0=py36_0
  - docutils=0.14=py36h6012d8f_0
  - entrypoints=0.2.3=py36hfd66bb0_2
  - et_xmlfile=1.0.1=py36h3d2d736_0
  - freetype=2.9.1=ha9979f8_1
  - gast=0.2.0=py36_0
  - gensim=3.4.0=py36hfa6e2cd_0
  - grpcio=1.12.1=py36h1a1b453_0
  - h5py=2.8.0=py36h3bdd7fb_1
  - hdf5=1.10.2=hac2f561_1
  - html5lib=0.9999999=py36_0
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=ha66f8fd_1
  - idna=2.7=py36_0
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.2.1=py36_0
  - jdcal=1.4=py36_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36_0
  - jmespath=0.9.3=py36_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36h6d89b47_1
  - jupyter_core=4.4.0=py36_0
  - keras=2.2.0=0
  - keras-applications=1.0.2=py36_0
  - keras-base=2.2.0=py36_0
  - keras-gpu=2.2.0=0
  - keras-preprocessing=1.0.1=py36_0
  - kiwisolver=1.0.1=py36h6538335_0
  - libpng=1.6.34=h79bbb47_0
  - libprotobuf=3.5.2=he0781b1_0
  - libsodium=1.0.16=h9d3ae62_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=2.6.11=py36_0
  - markupsafe=1.0=py36hfa6e2cd_1
  - matplotlib=2.2.3=py36hd159220_0
  - mistune=0.8.3=py36hfa6e2cd_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.1=py36h452e1ab_0
  - mkl_random=1.0.1=py36h9258bd6_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.3.1=py36h8dc0fde_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - notebook=5.5.0=py36_0
  - numpy=1.14.5=py36h9fa60d3_3
  - numpy-base=1.14.5=py36h5c71026_3
  - openpyxl=2.5.4=py36_0
  - openssl=1.0.2p=hfa6e2cd_0
  - pandas=0.23.1=py36h830ac7b_0
  - pandoc=2.2.1=h1a437c5_0
  - pandocfilters=1.4.2=py36h3ef6317_1
  - parso=0.2.1=py36_0
  - pickleshare=0.7.4=py36h9de030f_0
  - pip=10.0.1=py36_0
  - prompt_toolkit=1.0.15=py36h60b8f86_0
  - protobuf=3.5.2=py36h6538335_0
  - pycparser=2.18=py36_1
  - pygments=2.2.0=py36hb010967_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36_1
  - pyqt=5.9.2=py36h1aa27d4_0
  - pysocks=1.6.8=py36_0
  - python=3.6.6=hea74fb7_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pywinpty=0.5.4=py36_0
  - pyyaml=3.12=py36h1d1928f_1
  - pyzmq=17.0.0=py36hfa6e2cd_3
  - qt=5.9.6=vc14h62aca36_0
  - qtconsole=4.3.1=py36h99a29a9_0
  - requests=2.19.1=py36_0
  - s3transfer=0.1.13=py36_0
  - scikit-learn=0.19.1=py36h53aea1b_0
  - scipy=1.1.0=py36h672f292_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h6538335_0
  - six=1.11.0=py36h4db2310_1
  - smart_open=1.6.0=py36_0
  - sqlite=3.24.0=h7602738_0
  - tabulate=0.8.2=py36_0
  - tensorboard=1.8.0=py36he025d50_0
  - tensorflow=1.8.0=0
  - tensorflow-base=1.8.0=py36h1a1b453_0
  - tensorflow-gpu=1.8.0=h21ff451_0
  - tensorflow-gpu-base=1.8.0=py36h376609f_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h2698cfe_0
  - tornado=5.0.2=py36hfa6e2cd_0
  - traitlets=4.3.2=py36h096827d_0
  - urllib3=1.23=py36_0
  - vc=14.1=h0510ff6_3
  - vs2015_runtime=15.5.2=3
  - wcwidth=0.1.7=py36h3d5aa90_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - win_inet_pton=1.0.1=py36_1
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - xlrd=1.1.0=py36_1
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.2.5=he025d50_1
  - zlib=1.2.11=h8395fce_2

