name: tf18
channels:
  - plotly
  - anaconda
  - defaults
dependencies:
  - beautifulsoup4=4.7.1
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - openssl=1.1.1
  - soupsieve=1.8
  - absl-py=0.2.2
  - arrow-cpp=0.11.1
  - asn1crypto=0.24.0
  - astor=0.6.2
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=1.5.0
  - boto=2.49.0
  - boto3=1.8.2
  - botocore=1.11.2
  - cffi=1.11.5
  - chardet=3.0.4
  - colorama=0.3.9
  - cryptography=2.4.2
  - cudatoolkit=9.0
  - cudnn=7.1.4
  - cycler=0.10.0
  - cython=0.28.4
  - decorator=4.3.0
  - docutils=0.14
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - fastparquet=0.1.6
  - freetype=2.9.1
  - gast=0.2.0
  - gensim=3.4.0
  - gflags=2.2.2
  - glog=0.3.5
  - grpcio=1.12.1
  - h5py=2.8.0
  - hdf5=1.10.2
  - html5lib=0.9999999
  - icc_rt=2017.0.4
  - icu=58.2
  - idna=2.7
  - intel-openmp=2018.0.3
  - ipykernel=4.8.2
  - ipython=6.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - jdcal=1.4
  - jedi=0.12.0
  - jinja2=2.10
  - jmespath=0.9.3
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - keras=2.2.0
  - keras-applications=1.0.2
  - keras-base=2.2.0
  - keras-gpu=2.2.0
  - keras-preprocessing=1.0.1
  - kiwisolver=1.0.1
  - libboost=1.67.0
  - libpng=1.6.35
  - libprotobuf=3.5.2
  - libsodium=1.0.16
  - llvmlite=0.26.0
  - lz4-c=1.8.1.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=2.6.11
  - markupsafe=1.0
  - matplotlib=2.2.3
  - mistune=0.8.3
  - mkl=2018.0.3
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - more-itertools=4.3.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - nltk=3.4
  - notebook=5.5.0
  - numba=0.41.0
  - numpy=1.14.5
  - numpy-base=1.14.5
  - openpyxl=2.5.4
  - pandas=0.23.1
  - pandoc=2.2.1
  - pandocfilters=1.4.2
  - parso=0.2.1
  - pickleshare=0.7.4
  - pip=10.0.1
  - plotly=3.4.1
  - pluggy=0.8.0
  - prompt_toolkit=1.0.15
  - protobuf=3.5.2
  - psutil=5.4.8
  - py=1.7.0
  - pyarrow=0.11.1
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pysocks=1.6.8
  - pytest=3.9.1
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pywinpty=0.5.4
  - pyyaml=3.12
  - pyzmq=17.0.0
  - qt=5.9.7
  - qtconsole=4.3.1
  - requests=2.19.1
  - retrying=1.3.3
  - s3transfer=0.1.13
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=39.2.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.11.0
  - smart_open=1.6.0
  - snappy=1.1.7
  - sqlite=3.26.0
  - tabulate=0.8.2
  - tensorboard=1.8.0
  - tensorflow=1.8.0
  - tensorflow-base=1.8.0
  - tensorflow-gpu=1.8.0
  - tensorflow-gpu-base=1.8.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.3.1
  - thrift=0.11.0
  - thrift-cpp=0.11.0
  - tornado=5.0.2
  - traitlets=4.3.2
  - urllib3=1.23
  - vc=14.1
  - vs2015_runtime=15.5.2
  - wcwidth=0.1.7
  - werkzeug=0.14.1
  - wheel=0.31.1
  - widgetsnbextension=3.2.1
  - win_inet_pton=1.0.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xlrd=1.1.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - zstd=1.3.3
  - plotly-orca=1.1.1
prefix: C:\Users\kin24\AppData\Local\conda\conda\envs\tf18

